[project]
name = "dotsy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
license = "GPL-3.0"
dependencies = ["pyqt6>=6.8.0"]

[project.scripts]
dotsy = "dotsy.main:main"
